### ISSUE TITLE
No matplotlib

### ISSUE THREAD

**Issue by alvarogares** [076923/python-image-preview#1]
Issue Type: <b>Bug</b>

I have downloaded the Python Image Preview program to be able to use the matplotlib. But when I run the program it tells me "ModulenotFoundError": No module named 'matplotlib'

Extension version: 0.0.8
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (12.44GB free)|
|Process Argv|C:\\Users\\Paco Mateo\\Desktop\\PYTHON GENERAL\\pruebas python\\#ejemplo matplotlib.py --crash-reporter-id 36d601e7-7d80-489f-852d-83d30c748b62|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306cf:30340756
bridge0708:30335490

```

</details>

**Comment by Dr-Electron** [comment]
Did you solve the problem?
You need to install matplotlib with `pip install matplotlib`
