### ISSUE TITLE
Could not work in Pytorch

### ISSUE THREAD

**Issue by BinsonW** [076923/python-image-preview#2]
I have tried this extention in Pytorch like this:

```python
import torch
a=torch.zeros((800,500))
b=1
```

The breakpoint is set on line 3. But during the debug, the **yellow prompt icon didn't show** at all.

But it **works for numpy**:

```python
import numpy as np
color=np.full((500,500,3),(255,0,0),np.uint8)
b=1
```

I'm using the Ubuntu 16.04.7, VSCode 1.60, Pytoch 1.7.1, Numpy 1.19.2

Do you have any advice? Thanks!

**Comment by 076923** [comment]
First of all, thank you for the question. I have updated extension. (0.0.9 update)

CUDA support and torch shape operations were improved.

**You can now use it like this:**

```Python
import torch

img1 = torch.full((500, 500), 127, dtype=torch.uint8)          # 1-Channel Gray Image
img2 = torch.zeros((1, 500, 500))                              # 1-Channel Black Image
img3 = torch.zeros((500, 500))                                 # 1-Channel Black Image
img4 = torch.full((3, 500, 500), 1.0, dtype=torch.float32)     # 3-Channel White Image
img5 = torch.full((500, 500), 0.5, device='cuda')              # 1-Channel Gray Imaeg
img6 = torch.rand_like(img5)                                   # 1-Channel Random Image
```
