### ISSUE TITLE
How to apply on C++ in vscode

### ISSUE THREAD

**Issue by huahangwxy** [076923/python-image-preview#4]
Hi:
This is really good tooling for OpenCV on python. But how to apply on C++ OpenCV. Is it easy to change?
I know the tooling on VS. But I prefer to use vscode to develop since brief interface and fast.

Thank you very much for help and indication!

**Comment by 076923** [comment]
Hi, huahangwxy.
Currently not supported in C++.
Currently, only works in Python.
Sorry for not being able to help, thank you for using it.
